### ISSUE TITLE
Errors in mod

### ISSUE THREAD

**Issue by reyzor1991** [ChasarooniZ/auto-chat-message-pruner#2]
https://github.com/ChasarooniZ/auto-chat-message-pruner/blob/e28c2c8d68cc232b9e51d0976cd5a25795423a60/scripts/module.js#L14

Need to change to `userId`

Also if PC create message - get error

<img width="1209" alt="image" src="https://github.com/user-attachments/assets/0feceff8-a04d-4997-9b4f-234bf68e0e41">

**Comment by ChasarooniZ** [comment]
fix
