### ISSUE TITLE
Cant install module.json

### ISSUE THREAD

**Issue by SoundSherpa** [ChasarooniZ/auto-chat-message-pruner#3]
Seems when trying to install module.json for a v12 instance I get the error message shown in the screenshot.
![image](https://github.com/user-attachments/assets/21bcf946-e641-4971-8a45-93f46074bfa4)

Foundry v12 Build 331

**Comment by ottyn** [comment]
Seeing these errors in the console when trying to install v1.0.2 from the Modules page in Foundry v12.331.

![image](https://github.com/user-attachments/assets/bbad085e-28b1-4807-af59-62b2cb3bce2a)
