### ISSUE TITLE
ChatMessage "XXX" does not exist!

### ISSUE THREAD

**Issue by Thrajnor** [ChasarooniZ/auto-chat-message-pruner#4]
Hi! Big fun especially when other pruner freezes my client for nor reason, sadly I get error messages every time there are more than one message send at once. For example, in savage worlds' system there is an end-turn initiative draw and this action can send few messages resulting in a following error when it reaches a threshold. Tried to fix it for a bit, but I lack knowledge on how to check if message exists before removing or something like that.

For now, I just run prone every now and then.

![image](https://github.com/user-attachments/assets/a20700b7-9725-45e1-acb0-67f79434caa4)

**Comment by ChasarooniZ** [comment]
I'll look into it!

**Comment by ChasarooniZ** [comment]
Should be fixed in newest release [1.0.5](https://github.com/ChasarooniZ/auto-chat-message-pruner/releases/tag/1.0.5)
